version: "2.0"

services:
  spa:
    image: map-spa
    ports:
      - 3001:80
    networks:
      - map
  
  api:
    image: map-api
    networks:
      - map
  
  db:
    image: mongo:latest
    volumes:
      - "dbdata:/data/db"
    networks:
      - map

  test:
    image: ubuntu:latest
    networks:
      - map
    command: bash -c "while :; do sleep 10; done"
  
volumes:
  dbdata:

networks:
  map: