version: "3.7"

services:
  spa:
    image: node:latest
    ports:
      - "${SPA_PORT}:3000"
    volumes:
      - "${PROJECT_LOCATION}:/usr/app"
    working_dir: /usr/app
    command: npm start
    networks:
      map:
        aliases:
          - spa

  
  api:
    image: node:latest
    ports:
      - "${API_PORT}:8000"
    volumes:
      - "${PROJECT_LOCATION}:/usr/app"
    working_dir: /usr/app
    command: bash -c "npm install && ./node_modules/.bin/nodemon --legacy-watch --exec 'node -r dotenv/config' api/server.js dotenv_config_path=${DOTENV_CONFIG_PATH_FOR_API}"
    networks:
      map:
        aliases:
          - api

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "dbdata-dev:/data/db"
      - "${MONGOD_CONF_LOCATION}:/etc/mongod.conf"
    networks:
      map:
        aliases:
          - db
  
  playground:
    image: node:latest
    volumes:
      - "${PROJECT_LOCATION}:/usr/app"
    working_dir: /usr/app
    command: bash -c "while :; do sleep 10; done"
    networks:
      map:
        aliases:
          - playground
  
volumes:
  dbdata-dev:

networks:
  map:
