version: "2.0"

services:
  spa:
    build:
      context: ./src
    env_file:
      - /etc/mappingviolence/spa/.env
    networks:
      - map
  
  api:
    build:
      context: ./api
    env_file:
      - /etc/mappingviolence/api/.env
    networks:
      - map
  
  db:
    image: mongo:latest
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    networks:
      - map

  test:
    image: ubuntu:latest
    networks:
      - map
    command: bash -c "while :; do sleep 10; done"
  
volumes:
  dbdata:

networks:
  map: