version: "2.0"

services:
  spa:
    image: cailyncodes/mappingviolence:spa-1.0.6
    env_file: .env
    networks:
      - map
  
  api:
    image: cailyncodes/mappingviolence:api-1.0.2
    env_file: ./api/.env
    networks:
      - map
  
  db:
    image: mongo:latest
    volumes:
      - "dbdata:/data/db"
    networks:
      - map

  test:
    image: ubuntu:latest
    networks:
      - map
    command: bash -c "while :; do sleep 10; done"
  
volumes:
  dbdata:

networks:
  map:
