version: "3.7"

services:
  spa:
    build:
      context: ./src
    env_file:
      - /etc/mappingviolence/spa/.env
    networks:
      - main
  
  api:
    build:
      context: ./api
    env_file:
      - /etc/mappingviolence/api/.env
    networks:
      - main
  
  db:
    image: mongo:latest
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    networks:
      - main

  proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ${NGINX_CONF}
        target: /etc/nginx/nginx.conf
    networks:
      - main

  test:
    image: ubuntu:latest
    networks:
      - main
    command: bash -c "while :; do sleep 10; done"
  
volumes:
  dbdata:

networks:
  main: